name: Testing pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_testing_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install backend dependencies
        run: npm install
      - name: Install frontend dependencies
        run: cd client && npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build:ui
      - name: Test
        run: npm run test
        env:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:run
          start: npm start
          wait-on: http://localhost:3001
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: fly.io deployment
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
